name: 2. Workflow con pull_request

on:
  pull_request:
    branches: [main]

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Ejecutar acción simple
        run: echo "Pull request detectado"

      - name: Registrar en LOG
        run: |
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] TRIGGER: pull_request - Pull request detectado hacia main." >> eventos.log

      - name: Guardar cambios en el LOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: actualizar eventos.log por evento pull_request"